underdog-tech/pinwheel-android-sdk

app/build.gradle, pinwheel-android/build.gradle, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/Pinwheel.kt, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/model/DeviceMetadata.kt, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/webview/PinwheelWebViewClient.kt
`{
...,
deviceMetadata: { os, manufacturer, model, product, device, hardware }
}`
Add device metadata to PINWHEEL_INIT event payload.
=> add device metadata to pinwheel init event payload

app/build.gradle, pinwheel-android/build.gradle, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/Pinwheel.kt, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/model/PinwheelEvent.kt
Adds `pendingRetry` to Error object types.
https://pinwheel.atlassian.net/browse/PP-4623
=> Release 03.25.21

app/build.gradle, pinwheel-android/build.gradle, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/Pinwheel.kt, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/model/PinwheelEvent.kt
* Revert "Adds pendingRetry to Error type (#22)"
This reverts commit c89a9b41dae945068c64d30c2a67448ad8fc3477.
* New minor version for retry rollback
* Removing bad files
> Description here
> Fix [#1]()
=> Revert retry (#24)

app/build.gradle, pinwheel-android/build.gradle, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/Pinwheel.kt, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/model/PinwheelEvent.kt
Adds pending retry functionality back.
https://pinwheel.atlassian.net/browse/PP-4623?atlOrigin=eyJpIjoiN2Q2MjYyODAwYzg2NGE3NWJiZmM0YjliZTUwMTg4YWUiLCJwIjoiaiJ9
=> Pending retry

app/build.gradle, pinwheel-android/build.gradle, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/Pinwheel.kt, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/model/PinwheelEvent.kt
Release pendingRetry for errors
=> Release v2.3.0

.circleci/config.yml, gradle.properties
I'd like to remove the beta deployment from this repo, for now at least. For one, I don't want to have this API key in the repo. Also, I'd like to re-think, and discuss the strategy for these deployments.
> Fix [#1]()
=> Beta build cleanup

README.md, app/build.gradle, pinwheel-android/build.gradle
Version bump for release 2.3.2. 
Updated the GitHub environment variable names to be more obvious.
> Fix [#1]()
=> Release 2.3.2

LICENSE, README.md, build.gradle, pinwheel-android/build.gradle, scripts/publish-module.gradle, scripts/publish-root.gradle
Add support for publishing to Maven Central
[PP-5282](https://pinwheel.atlassian.net/browse/PP-5282)
=> Add support for publishing to Maven Central

README.md, pinwheel-android/build.gradle, scripts/publish-module.gradle
Release 2.3.5
Fix issue with initializing on SDK 25 (#39)
=> Release 2.3.5

scripts/publish-module.gradle
Update license field to correctly identify MIT
https://pinwheel.atlassian.net/browse/PP-5448
#42
=> Update license field to correctly identify MIT

README.md, app/build.gradle, pinwheel-android/build.gradle
Release 
#43 - Update license fields
#41 - Bump dependenices
https://pinwheel.atlassian.net/browse/PP-5448
https://github.com/underdog-tech/pinwheel-android-sdk/issues/42
=> Release 2.3.6

README.md, app/build.gradle, pinwheel-android/build.gradle
Release for #45 
https://pinwheel.atlassian.net/browse/PP-5477
=> Release 2.3.7

README.md, app/build.gradle, pinwheel-android/build.gradle
=> Release 2.3.8

README.md, app/build.gradle, pinwheel-android/build.gradle
Release:
Add rules to prevent stripping of JS interfaces, and GSON events #47
=> Release 2.3.11

README.md, app/build.gradle, pinwheel-android/build.gradle
Release #64 - Add platformId to success event payload.
=> Release 2.3.13

app/build.gradle, pinwheel-android/build.gradle
Update core-ktx and appcompat packages
=> Update core-ktx and appcompat packages

.gitignore, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/model/PinwheelEvent.kt, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/webview/PinwheelJavaScriptInterface.kt
Add support for input_required event
=> Add support for input_required event

CHANGELOG.md, README.md, app/build.gradle, pinwheel-android/build.gradle
- PinwheelEventType.INPUT_REQUIRED
- Added by [Robby Abaya](https://github.com/rawbee) in Pull Request [#67](https://github.com/underdog-tech/pinwheel-android-sdk/pull/67).
=> Release 2.3.14

build.gradle, gradle/wrapper/gradle-wrapper.properties, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/model/PinwheelEvent.kt, pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/webview/PinwheelJavaScriptInterface.kt
Adds support for input_allocation event
=> Add support for input_allocation event

CHANGELOG.md, README.md, app/build.gradle, pinwheel-android/build.gradle
=> Release 2.3.15

pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/model/PinwheelEvent.kt
Add `target` to `PinwheelAllocation`
> Fix [#1]()
=> Add target field to PinwheelAllocation

CHANGELOG.md, README.md, app/build.gradle, pinwheel-android/build.gradle
> Description here
> Fix [#1]()
=> Release 2.3.16

CHANGELOG.md, README.md, app/build.gradle, pinwheel-android/build.gradle
> Description here
> Fix [#1]()
=> Release 2.3.17

Gemfile, Gemfile.lock
> Description here
> Fix [#1]()
=> Con 183 android sdk patch critical vulnerabilities

pinwheel-android/src/main/java/com/underdog_tech/pinwheel_android/Pinwheel.kt
Enables the DOM storage setting as Link leverages `localStorage`.
https://pinwheel.atlassian.net/browse/CON-529
=> Enable DOM storage

CHANGELOG.md, README.md, app/build.gradle, pinwheel-android/build.gradle
Included change from 2.3.17 -> 2.3.18: https://github.com/underdog-tech/pinwheel-android-sdk/pull/82
> Fix [#1]()
=> Release 2.3.18

CHANGELOG.md, app/src/main/java/com/underdog_tech/pinwheel_android_demo/ui/main/MainFragment.kt, app/src/main/java/com/underdog_tech/pinwheel_android_demo/ui/main/MainViewModel.kt
=> Update CHANGELOG and demo app

CHANGELOG.md, README.md
Update CHANGELOG and README for 2.4.5
=> Update CHANGELOG and README for 2.4.5
